name: Update container image

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    name: Build and push container image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4
      - name: docker login
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: docker build and push
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: |
            ghcr.io/kannadev/hazie.uk:${{ github.sha }}
            ghcr.io/kannadev/hazie.uk:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  update-bunny-container:
    name: Update container image on Magic Containers
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Update container image on Magic Containers
        uses: BunnyWay/actions/container-update-image@d15f94f8fd513950561a5996a40f99d1dd1c357c
        with:
          app_id: ${{ vars.APP_ID }}
          api_key: ${{ secrets.BUNNYNET_API_KEY }}
          container: hazie.uk
          image_tag: "${{ github.sha }}"

  clear-cache:
    name: Clear CDN cache
    runs-on: ubuntu-latest
    needs: update-bunny-container
    steps:
      - name: Clear CDN cache
        run: |
          sleep 90
          curl -X POST -H "Authorization: ${{ secrets.BUNNYNET_API_KEY }}" https://api.bunny.net/pullzone/6014008/purgeCache
